# Generated by Django 3.2.8 on 2021-10-28 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Chefe')),
            ],
            options={
                'verbose_name': 'Chefe',
                'verbose_name_plural': 'Chefes',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ingredients', models.TextField(verbose_name='Ingredientes')),
                ('time', models.IntegerField(verbose_name='Tempo de preparo (em minutos)')),
                ('difficulty', models.CharField(choices=[('1', 'Fácil'), ('2', 'Médio'), ('3', 'Difícil')], max_length=1, verbose_name='Dificuldade de preparo')),
                ('method', models.TextField(verbose_name='Método de preparo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cookbook.chef', verbose_name='Chef')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
            },
        ),
    ]
