# Generated by Django 3.2.8 on 2021-10-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_rename_recipes_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='chef',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='user',
        ),
        migrations.AddField(
            model_name='chef',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
