# Generated by Django 3.2.8 on 2021-10-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_auto_20211028_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chef',
            options={'verbose_name': 'Chef', 'verbose_name_plural': 'Chefes'},
        ),
    ]
