# Generated by Django 3.2.8 on 2021-10-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_alter_chef_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='portions',
            field=models.IntegerField(default=1, verbose_name='Numero de Porções que a Receita rende'),
        ),
    ]
